### ISSUE TITLE
leo.org

### ISSUE THREAD

**Issue by UCyborg** [martok/palefill#44]
Another potential candidate that can (mostly, hopefully) be easily fixed by this rule:

*.leo.org
    std-ShadowDOM

There's a [discussion thread](https://forum.palemoon.org/viewtopic.php?f=70&t=28785) about it opened on Pale Moon forum.

**Comment by martok** [comment]
Hm, there are some problems with template elements that aren't even visible appearing in front, so LEO's forum is basically unusable because dropdown menus intercept the actual content. But the dictionary part seems to work, so I'll commit that for now.

Looks like this is the same problem we have with Virustotal (#39). Apparently ShadyDOM still requires the `:host` pseudoelement. ShadyCSS looks like it's not polyfillable but requires a different programming style?

UXP issue [1375](https://repo.palemoon.org/MoonchildProductions/UXP/issues/1375#issuecomment-10271).

**Comment by AstroSkipper** [comment]
> But the dictionary part seems to work, so I'll commit that for now.

No, unfortunately not. When looking up a word in the dictionary, the expanding more results doesn't work, either. I reported this issue here: [MSFN - My Browser Builds (Part 3)](https://msfn.org/board/topic/182647-my-browser-builds-part-3/?do=findComment&comment=1227886)

**Comment by martok** [comment]
Looking resolved now in PM 32.0, the weird "invisible hover" elements are gone.

**Comment by Vangelis66** [comment]
> Looking resolved now in PM 32.0,

... 😞 Sadly, the "**more nouns**" issue reported by @AstroSkipper in [this](https://github.com/martok/palefill/issues/44#issuecomment-1295866806) comment still persists: 

![Leo](https://user-images.githubusercontent.com/9669492/216782373-34199852-2fc1-4834-8886-eb4d381983cd.png)

To clarify, `more nouns` **can't be expanded** when `palefill` is **installed and enabled**; OTOH, it can be expanded when `palefill` **isn't enabled/installed** (but then page layout is **broken** 😢 ); this issue should be re-opened/re-visited 😉 ...
